### PR TITLE
Typos in fares_note; Wear version

### PR DESCRIPTION
**Pull request by marcasoduinn**
Committing typo changes to fares_note.
Updating translations in Wear version in line with Mobile.

### CODE REVIEW

**Comment by thecosmicfrog** [comment]
Looks good! Thanks @marcasoduinn - changes now merged.

**Comment by thecosmicfrog** [comment]
Hi @marcasoduinn. I will be releasing a new version of Luas at a Glance shortly. Would you like your name included in the "Irish translations by" section?

All the best,
Aaron

**Comment by marcasoduinn** [comment]
Ba mhaith liom, cinnte... I would to be sure!

A friend of mine reviewed the translations, and had no suggestions.

On final change I might make is "Am" to "Ann"... this is how "due" is
translated on the Dublin Bus displays. I'll edit the database tomorrow, and
start the usual PR.

Thanks again,
Marcas

**Comment by marcasoduinn** [comment]
I've seen the latest updates, the Irish looks great!

I find i have a problem on my phone with this update. If anything happens
to the screen, even a rotation, the timetable reverts to the Red Line. I
keep having to change back to the Green Line.  (Is this a "default state"
issue, perhaps?).

Another small issue is that the status message still says " ... mar is
gnách" (on the Irish side at least, even when all hell like storm Ali has
broken loose, and the status colour had changed to red.

Beir bua,
Marcas.

On 2 DFómh 2018 20:04, "marcas" <marcas.oduinn@gmail.com> wrote:

Ba mhaith liom, cinnte... I would to be sure!

A friend of mine reviewed the translations, and had no suggestions.

On final change I might make is "Am" to "Ann"... this is how "due" is
translated on the Dublin Bus displays. I'll edit the database tomorrow, and
start the usual PR.

Thanks again,
Marcas

**Pull request merged**
